### ISSUE TITLE
Version 1.0.11 : Missing comma, in ext_tables.sql

### ISSUE THREAD

**Issue by sypets** [Klickfabrik/kf_backend_mod#1]
There is a comma missing in ext_tables.sql:

https://github.com/Klickfabrik/kf_backend_mod/blob/d388b76feb2e79a4ba48477042589b1fb93d3286/ext_tables.sql#L9

This will cause the "DB compare" to fail.

**Comment by Klickfabrik** [comment]
Thanks a lot"


Beste Grüße
Marc
 
--------------------------------------------------------
klickfabrik
Marc Finnern
Herbststraße 73
47137 Duisburg
—
Tel.: +4920355248302
Tel.: +491721356103


Finanzamt Duisburg-Hamborn
USt.-ID: DE286830003
Inhaber: Marc Finnern
--------------------------------------------------------
www.klickfabrik.net
marc@klickfabrik.net

Am 22. November 2017 um 11:52:47, Sybille Peters (notifications@github.com) schrieb:

There is a comma missing in ext_tables.sql:

https://github.com/Klickfabrik/kf_backend_mod/blob/d388b76feb2e79a4ba48477042589b1fb93d3286/ext_tables.sql#L9

This will cause the "DB compare" to fail.

**Comment by sypets** [comment]
Thanks for the fast response!

VG, 
Sybille
